
/* modules/hopf.js */
/* GENChase: Hopf fibration drawn by stereographic projection. Fibres are circles, pairwise linked. Linking number is 1 by construction. */
(function () {
  'use strict';
  const U = Studio.util;
  const GEOM = 'geom', PAINT = 'paint';
  const f2 = v => v.toFixed(2);
  const f3 = v => v.toFixed(3);
  const ASPECTS = { '1:1': 1, '4:5': 1.25, '5:4': 0.8, '3:2': 2 / 3, '16:9': 9 / 16 };
  const RANGE = (group, key, label, kind, min, max, step, fmt, extra) =>
    Object.assign({ group, key, label, type: 'range', kind, min, max, step, fmt }, extra || {});
  const Pal = Studio.PALETTES;
  const pre = (label, p, pal) => ({ label, p, palette: pal });

  // The Grid slider and sanitize() read the same bounds, so no slider position is clamped away.
  const GRID_MIN = 128, GRID_MAX = 224;
  const SCHEMA = [
    RANGE('Field', 'grid', 'Grid', GEOM, GRID_MIN, GRID_MAX, 16, v => v + ''),
    { group: 'Field', key: 'aspect', label: 'Sheet', type: 'seg', kind: GEOM, options: [['1:1', '1:1'], ['4:5', '4:5'], ['5:4', '5:4'], ['16:9', '16:9']] },
    RANGE('Fibration', 'fibres', 'Fibres', GEOM, 12, 80, 2, v => v + ''),
    RANGE('Fibration', 'twist', 'Base tilt', GEOM, 0, 1.4, 0.05, f2),
    { group: 'Fibration', key: 'kind', label: 'Draw', type: 'seg', kind: GEOM, options: [['fibres', 'Fibres'], ['tori', 'Nested tori'], ['base', 'Base S²']] },
    { group: 'Picture', key: 'view', label: 'View', type: 'seg', kind: PAINT, options: [['int', 'Field'], ['log', 'Log']] },
    RANGE('Picture', 'exposure', 'Exposure', PAINT, 0.4, 2.2, 0.05, f2),
  ];
  const DEFAULTS = { grid: 192, aspect: '1:1', fibres: 36, twist: 0.35, kind: 'fibres', view: 'int', exposure: 1 };
  const PRESETS = {
    linked: pre('Linked circles', { kind: 'fibres', fibres: 40, twist: 0.4 }, Pal.nightshade),
    tori: pre('Nested tori', { kind: 'tori', fibres: 48, twist: 0.2 }, Pal.ember),
    poles: pre('Near poles', { twist: 0.05, fibres: 28, kind: 'fibres' }, Pal.harbor),
    dense: pre('Dense', { fibres: 48, kind: 'fibres' }, Pal.thermal),
    base: pre('Base S²', { kind: 'base', fibres: 24 }, Pal.glacier),
    sparse: pre('Sparse', { fibres: 16, twist: 0.7, kind: 'fibres' }, Pal.kiln),
  };

  function surprise(rng) { return { fibres: rng.int(20, 64), twist: rng.range(0.1, 0.9), kind: rng.pick(['fibres','fibres','tori']) }; }
  function sanitize(s) { s.grid = Math.max(GRID_MIN, Math.min(GRID_MAX, Math.round(s.grid / 16) * 16)); }
  function hopfPoint(theta, phi, t) {
    const a=Math.cos(theta/2), b=Math.sin(theta/2), den=1-b*Math.sin(t+phi);
    return [a*Math.cos(t)/den,a*Math.sin(t)/den,b*Math.cos(t+phi)/den];
  }
  function fibre(theta,phi,n){return Array.from({length:n},(_,j)=>hopfPoint(theta,phi,2*Math.PI*j/n));}
  // Midpoint quadrature of the Gauss integral on two closed polygonal samples.
  function gaussLink(a,b) {
    let integral=0;
    for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++){
      const p=a[i],q=a[(i+1)%a.length],r=b[j],s=b[(j+1)%b.length];
      const d=[(p[0]+q[0]-r[0]-s[0])/2,(p[1]+q[1]-r[1]-s[1])/2,(p[2]+q[2]-r[2]-s[2])/2];
      const u=q.map((v,k)=>v-p[k]),v=s.map((x,k)=>x-r[k]);
      const cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];
      integral+=(d[0]*cross[0]+d[1]*cross[1]+d[2]*cross[2])/Math.hypot(...d)**3;
    }
    return integral/(4*Math.PI);
  }
  Studio.register({
    id: 'hopf', name: 'Hopf Fibration', tab: 'Hopf',
    subtitle: 'every circle linked with every other · 1931',
    order: 57,
    equation: 'η: S³ → S²,   η(z1,z2) = (2 z1 z2-bar, |z1|²-|z2|²),   fibres = circles,   lk = 1',
    credit: 'H. Hopf, Math. Ann. 104, 637 (1931). The third homotopy group of the 2-sphere is not zero: π₃(S²) = ℤ, generated by this map. Stereographic projection from S³ turns the fibres into a nesting of linked circles in R³, then onto the plate. No two fibres are unlinked.',
    blurb: 'A 3-sphere worth of circles, each the preimage of a point of S², and every pair is linked exactly once. There is no unlink hiding in the stack. The plate is a stereographic view of those fibres, coloured by the base. The status estimates the absolute Gauss linking integral for two displayed fibres using 180 and 360 segments. Their change is a refinement indicator, not a rigorous error bound; the exact topological magnitude is one.',
    schema: SCHEMA, defaults: DEFAULTS, presets: PRESETS, closedGroups: ['Picture'],
    hints: { Fibration: 'Nested tori is the same fibration grouped by latitude on the base S².' },
    palette: true, defaultPalette: 'nightshade', surprise, sanitize,
    create(host) {
      const canvas = host.canvas, ctx = canvas.getContext('2d', { alpha: false });
      let W = 0, H = 0, field, metric = 0, extra = 0, linkChange = 0, buf, img;
      function sizeFrom(s) {
        const a = ASPECTS[s.aspect] || 1, g = s.grid | 0;
        return { W: g, H: Math.max(48, Math.round(g * a)) };
      }
      function compute() {
        const s = host.getState();
        const sz = sizeFrom(s); W = sz.W; H = sz.H;
        field = new Float32Array(W * H);
        const rng = U.makeRng(String(s.seed) + '/x');

        const nF = s.fibres | 0, tilt = s.twist;
        field.fill(0);
        function splat(x, y, wgt) {
          const xi = Math.floor(x), yi = Math.floor(y);
          if (xi < 0 || yi < 0 || xi >= W - 1 || yi >= H - 1) return;
          const fx = x - xi, fy = y - yi;
          field[yi * W + xi] += wgt * (1 - fx) * (1 - fy);
          field[yi * W + xi + 1] += wgt * fx * (1 - fy);
          field[(yi + 1) * W + xi] += wgt * (1 - fx) * fy;
          field[(yi + 1) * W + xi + 1] += wgt * fx * fy;
        }
        for (let f = 0; f < nF; f++) {
          const th = Math.PI * (f + 0.5) / nF, ph = (f * 2.399 + tilt) % (Math.PI * 2);
          for (let spt = 0; spt < 180; spt++) {
            const psi = spt * Math.PI * 2 / 180;
            const [X,Y,Z] = hopfPoint(th,ph,psi);
            const px = (0.5 + 0.28 * X) * W, py = (0.5 + 0.28 * Y) * H;
            const wgt = s.kind === 'base' ? (0.4 + 0.6 * (Z * 0.5 + 0.5)) : (s.kind === 'tori' ? 0.35 + 0.7 * Math.sin(th) * Math.sin(th) : 0.7);
            splat(px, py, wgt);
            splat(px + 1, py, wgt * 0.5);
            splat(px, py + 1, wgt * 0.5);
            splat(px - 1, py, wgt * 0.5);
            splat(px, py - 1, wgt * 0.5);
          }
        }
        const f1=Math.floor(nF/4),f2=Math.floor(3*nF/4);
        const params=f=>[Math.PI*(f+.5)/nF,(f*2.399+tilt)%(2*Math.PI)];
        const [th1,ph1]=params(f1),[th2,ph2]=params(f2);
        const coarse=Math.abs(gaussLink(fibre(th1,ph1,180),fibre(th2,ph2,180)));
        metric=Math.abs(gaussLink(fibre(th1,ph1,360),fibre(th2,ph2,360)));
        linkChange=Math.abs(metric-coarse);
        extra = nF;
        for (let i = 0; i < field.length; i++) field[i] = Math.log(1 + field[i]);

        buf = document.createElement('canvas'); buf.width = W; buf.height = H;
        img = buf.getContext('2d').createImageData(W, H);
      }


      function paint() {
        if (!field) return;
        const s = host.getState();
        const pal = Array.isArray(s.palette) && s.palette.length ? s.palette : ['#111', '#eee'];
        const ramp = U.makeRamp(pal, s.bg || '#111');
        const data = img.data;
        const exp = isFinite(s.exposure) && s.exposure > 0 ? s.exposure : 1;
        let lo = Infinity, hi = -Infinity;
        for (let i = 0; i < field.length; i++) { const v = field[i]; if (v < lo) lo = v; if (v > hi) hi = v; }
        const span = (hi - lo) || 1, logv = s.view === 'log';
        for (let i = 0; i < field.length; i++) {
          let t = (field[i] - lo) / span;
          if (logv) t = Math.log(1.001 + 9 * Math.max(0, t)) / Math.log(10);
          t = U.clamp(t * exp, 0, 1);
          const c = ramp(isFinite(t) ? t : 0);
          const o = i * 4; data[o] = c[0]; data[o + 1] = c[1]; data[o + 2] = c[2]; data[o + 3] = 255;
        }
        buf.getContext('2d').putImageData(img, 0, 0);
        ctx.imageSmoothingEnabled = false;
        ctx.fillStyle = s.bg || '#111';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(buf, 0, 0, canvas.width, canvas.height);
      }

      function status() {
        host.setStatus('<span>'+(extra|0)+' fibres</span>' +
          U.stats.compare({ label: '|Gauss link|, 360 segments', measured: metric, expected: 1, reference: 'linking number', basis: 'deterministic', digits: 7 }) +
          '<span>refinement change, 180→360 segments '+linkChange.toExponential(2)+'</span>');
      }

      return {
        aspect(s) { return ASPECTS[s.aspect] || 1; },
        fieldCells() { return W && H ? [W, H] : null; },
        regenerate() { compute(); paint(); status(); },
        repaint() { paint(); status(); },
        resize() { paint(); },
        pause() {},
        resume() { paint(); },
        async exportPNG(w, h) {
          if (!buf) throw new Error('nothing to export');
          const s = host.getState();
          const c = document.createElement('canvas'); c.width = w; c.height = h;
          const g = c.getContext('2d', { alpha: false });
          g.imageSmoothingEnabled = false;
          g.fillStyle = s.bg || '#111'; g.fillRect(0, 0, w, h);
          g.drawImage(buf, 0, 0, w, h);
          return U.toBlob(c);
        },
      };

    },
  });
})();
