// Public ledger of volunteer computer time. Writes COMPUTE.md from shared job records and the vortex leaderboard.
// node tools/compute-ledger.js [--check]
'use strict';
const fs = require('node:fs'), path = require('node:path');
const { WATTS_PER_BUSY_CORE } = require('../apps/validate/compute');
const root = path.resolve(__dirname, '..'), out = path.join(root, 'COMPUTE.md');
const readJson = f => { try { return JSON.parse(fs.readFileSync(f, 'utf8')); } catch { return null; } };
function jobs() { // shared evidence pull requests land in validation/submissions/<job id>/job.json
  const dir = path.join(root, 'validation/submissions'); if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).sort().map(id => readJson(path.join(dir, id, 'job.json'))).filter(j => j && typeof j === 'object');
}
function ledger() {
  const rows = {}, total = { jobs: 0, recorded: 0, cpuSeconds: 0, wallSeconds: 0, joules: 0, measuredJobs: 0, machines: new Set() };
  for (const j of jobs()) {
    const c = j.compute || {}, key = (j.input?.workspace || '?') + ' / ' + (j.input?.mode || '?'), r = rows[key] ||= { jobs: 0, cpuSeconds: 0, wallSeconds: 0, unrecorded: 0 };
    total.jobs++; r.jobs++; total.machines.add(j.input?.machineSlug || 'unlabelled');
    if (Number.isFinite(c.wallSeconds)) { total.wallSeconds += c.wallSeconds; r.wallSeconds += c.wallSeconds; }
    if (c.recorded && Number.isFinite(c.cpuSeconds)) { total.recorded++; total.cpuSeconds += c.cpuSeconds; r.cpuSeconds += c.cpuSeconds; } else r.unrecorded++;
    if (Number.isFinite(c.energy?.joules)) { total.joules += c.energy.joules; total.measuredJobs++; }
  }
  const board = readJson(path.join(root, 'experiments/results/vortex-collapse-leaderboard.json'));
  return { rows, total, vortex: board?.compute || null };
}
const hours = s => (s / 3600).toFixed(2), wh = s => `${(s * WATTS_PER_BUSY_CORE[0] / 3600).toFixed(1)} to ${(s * WATTS_PER_BUSY_CORE[1] / 3600).toFixed(1)} Wh`;
function render({ rows, total, vortex }) {
  const lines = ['# Computer time', '',
    'Generated by `node tools/compute-ledger.js` from shared job records and the vortex-collapse leaderboard. Do not edit by hand.', '',
    'Everything the studio proves or measures runs on ordinary computers: the maintainers\' and those of volunteers who run',
    '[the local validator](apps/validate/HEADLESS.md). This page counts that time so the cost of each result is visible.', '',
    '## Shared volunteer jobs', ''];
  if (!total.jobs) lines.push('No job has been shared through an evidence pull request yet.', '');
  else {
    lines.push(`${total.jobs} shared jobs from ${total.machines.size} machine label(s): ${hours(total.cpuSeconds)} CPU hours measured over ${hours(total.wallSeconds)} hours of running time.`,
      `Energy: ${total.measuredJobs ? `${(total.joules / 3600).toFixed(1)} Wh measured on ${total.measuredJobs} job(s); ` : ''}about ${wh(total.cpuSeconds)} estimated for all measured CPU time.`, '',
      '| Job | Jobs | CPU hours | Running hours | Jobs without a CPU record |', '|---|---:|---:|---:|---:|',
      ...Object.entries(rows).sort().map(([k, r]) => `| ${k} | ${r.jobs} | ${hours(r.cpuSeconds)} | ${hours(r.wallSeconds)} | ${r.unrecorded} |`), '');
  }
  lines.push('## Least-winding vortex search', '');
  if (!vortex) lines.push('No verified results yet.', '');
  else {
    lines.push(`${vortex.seeds} seeds in ${vortex.files} result files from ${vortex.machines} machine label(s): ${vortex.cpuHours.toFixed(2)} CPU hours, about ${vortex.estimatedWattHours.map(v => v.toFixed(1)).join(' to ')} Wh estimated${vortex.filesMeasured ? `, ${(vortex.measuredJoules / 3600).toFixed(1)} Wh measured on ${vortex.filesMeasured} file(s)` : ''}. The maintainers' own runs are included.`, '',
      '| α | N | Seeds | CPU hours | Independent reruns of a block | Reruns that disagreed |', '|---:|---:|---:|---:|---:|---:|',
      ...vortex.byCase.map(c => `| ${c.alpha} | ${c.N} | ${c.seeds} | ${c.cpuHours.toFixed(3)} | ${c.independentReruns} | ${c.disagreements.length} |`), '',
      'A rerun of the same seed block on another machine must reproduce the block\'s results digest. A disagreement shows platform dependence, not an error in either machine.', '');
  }
  lines.push('## How these numbers are made', '',
    '- **CPU time is measured.** Each job runs under the POSIX shell, whose `times` builtin reports the user and system time of the command and of every descendant it waited for. Detached descendants and stopped jobs are not counted. The vortex search also times each seed itself.',
    '- **Energy is measured only where the operating system allows it.** On Linux with a readable RAPL counter, the job records the processor package energy. That figure includes anything else running at the time.',
    `- **Everywhere else energy is an estimate.** It is CPU time multiplied by ${WATTS_PER_BUSY_CORE[0]} to ${WATTS_PER_BUSY_CORE[1]} W per busy core, a range that covers phone-class efficiency cores through desktop cores. It excludes memory, display, cooling and the rest of the machine, so treat it as an order of magnitude.`,
    '- **Contributors report their own numbers.** A result can be re-verified; its compute cannot, only rerun.',
    '- **Not counted here:** the computing behind the AI assistance used to write code and papers in this repository. The provider does not report it here, and it is not estimated.', '');
  return lines.join('\n');
}
const text = render(ledger());
if (process.argv.includes('--check')) {
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) { console.error('COMPUTE.md is out of date. Run node tools/compute-ledger.js.'); process.exit(1); }
  console.log('COMPUTE.md is current.');
} else { fs.writeFileSync(out, text); console.log('Wrote COMPUTE.md'); }
