// node tools/science.js [--write]: validate records and render the coverage report.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');
const catalog = JSON.parse(read('techniques.json')).techniques;
const records = JSON.parse(read('validation/techniques.json'));
const statuses = ['unvalidated', 'partially validated', 'validated within stated limits'];
const assert = (ok, why) => { if (!ok) throw Error(why); };
const validFile = f => typeof f === 'string' && !path.isAbsolute(f) && !f.split('/').includes('..') && fs.existsSync(path.join(root, f));
try {
  assert(Array.isArray(records), 'Expected validation record array');
  const ids = new Set();
  for (const r of records) {
    assert(!ids.has(r.id), 'Duplicate validation id: ' + r.id); ids.add(r.id);
    const m = catalog.find(m => m.id === r.id);
    assert(m, 'Unknown technique: ' + r.id);
    assert(statuses.includes(r.status), 'Invalid status: ' + r.id);
    assert(validFile(r.source), 'Missing source: ' + r.id);
    assert(read(r.source).includes("id: '" + r.id + "'"), 'Source/id mismatch: ' + r.id);
    assert(crypto.createHash('sha256').update(read(r.source)).digest('hex') === r.sourceSha256, 'Source changed; review validation record: ' + r.id);
    assert(r.reference === m.credit && r.equation === m.equation, 'Catalog reference drift: ' + r.id);
    for (const key of ['limitations', 'remaining']) assert(Array.isArray(r[key]) && r[key].length && r[key].every(x => typeof x === 'string' && x.trim()), 'Missing ' + key + ': ' + r.id);
    for (const kind of ['numerical', 'print']) {
      assert(Array.isArray(r[kind]), 'Missing evidence list: ' + r.id);
      for (const e of r[kind]) {
        assert(validFile(e.test), 'Missing evidence test: ' + r.id);
        for (const k of ['scope', 'criteria', 'limitations']) assert(typeof e[k] === 'string' && e[k].trim(), 'Missing evidence ' + k + ': ' + r.id);
      }
    }
    if (r.status !== 'unvalidated') assert(r.numerical.length, 'Status requires numerical evidence: ' + r.id);
    if (r.status === 'validated within stated limits') {
      assert(r.print.length && r.domain && /^\d{4}-\d{2}-\d{2}$/.test(r.reviewed || '') && validFile(r.results), 'Full status requires print evidence, domain, review date and results: ' + r.id);
    }
  }
  assert(catalog.every(m => ids.has(m.id)), 'Missing technique validation records');
  const counts = statuses.map(s => `${records.filter(r => r.status === s).length} ${s}`).join('; ');
  const safe = s => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const rows = records.map(r => `| [${r.id}](${r.source}) | ${r.status} | ${r.numerical.map(e => '[' + path.basename(e.test) + '](' + e.test + ')').join(', ') || 'None registered'} | ${r.print.length ? 'Limited evidence recorded' : 'Not scientifically validated'} |`).join('\n');
  const report = `# Scientific validation coverage\n\n> [!IMPORTANT]\n> These are evidence labels, not certification that every simulation matches its paper.\n> ${counts}.\n\nGenerated by \`node tools/science.js --write\` from [records](validation/techniques.json).\nRead the [validation contract](validation/README.md) for acceptance rules and audit priorities.\n\nA passing inventory check verifies coverage and source fingerprints. Numerical tests must also\nrun successfully; fingerprints do not validate mathematics. Runtime, determinism and print\nsharpness checks are separate from scientific accuracy. No technique currently has complete\nregistered numerical-and-print validation.\n\n| Technique / source | Scientific status | Numerical test | Print accuracy |\n|---|---|---|---|\n${rows}\n\n## Recorded limitations\n\n${records.filter(r => r.numerical.length).map(r => '### ' + r.id + '\n\n' + r.limitations.map(s => '- ' + safe(s)).join('\n') + '\n').join('\n')}\nThe remaining records retain each catalog equation and reference as a review target. They do not\nclaim those descriptions have been checked against the primary paper. Full parameter, precision,\nboundary-condition, convergence and print-state reviews remain outstanding where recorded.\n`;
  if (process.argv.includes('--write')) fs.writeFileSync(path.join(root, 'VALIDATION.md'), report);
  else assert(read('VALIDATION.md') === report, 'VALIDATION.md is stale; run node tools/science.js --write');
  console.log('Coverage records OK: ' + counts);
} catch (e) { console.error(e.message); process.exitCode = 1; }
