'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const {reference,inspect,enumerate,geometry}=require('./lib/ust-reference');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'src/modules/ust.js'),'utf8'),engine=fs.readFileSync(path.join(root,'src/shared/engine.js'),'utf8'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const makeRng=new Function(engine.slice(engine.indexOf('  function makeRng'),engine.indexOf('  function makeNoise'))+'return makeRng;')();
let clock=0;const hooks={};new Function('Studio','hooks','performance',source.replace('  Studio.register({','  hooks.makeWilson=makeWilson;\n  Studio.register({'))({util:{},PALETTES:{},register(){}},hooks,{now:()=>clock++});
function actual(W,H,root,wrap,seed,chunk=Infinity,bias=false){let rng=makeRng(seed);if(bias){const base=rng;rng=()=>base()**2;}const a=hooks.makeWilson(W,H,root,wrap,rng);while(!a.done())a.step(chunk);return{par:Array.from(a.next,(_,i)=>i===root?-1:a.nb(i,a.next[i])),walks:a.steps()};}
function sampling(){const rows=[];for(const [W,H,wrap,samples]of[[2,2,false,12000],[2,3,false,24000],[3,3,false,24000],[3,3,true,24000]]){
 const exact=enumerate(W,H,wrap),counts=new Map(exact.counts),edgeCounts=new Array(exact.edges.length).fill(0),edgeIndex=new Map(exact.edges.map(([a,b],i)=>[a+':'+b,i]));
 for(let i=0;i<samples;i++){const a=actual(W,H,i%(W*H),wrap,'ust-stat-'+W+'-'+H+'-'+wrap+'-'+i),b=inspect(a.par,W,H,i%(W*H),wrap),key=b.edges.join('|');assert(counts.has(key),'Unexpected tree');counts.set(key,counts.get(key)+1);for(const edge of b.edges)edgeCounts[edgeIndex.get(edge)]++;}
 const tests=counts.size+edgeCounts.length,alpha=.001,bound=Math.sqrt(Math.log(2*tests/alpha)/(2*samples)),probability=1/counts.size,maxTreeError=Math.max(...[...counts.values()].map(v=>Math.abs(v/samples-probability))),maxEdgeError=Math.max(...edgeCounts.map((n,i)=>Math.abs(n/samples-exact.marginals[i])));assert(maxTreeError<bound&&maxEdgeError<bound);
 rows.push({grid:[W,H],boundary:wrap?'torus':'rectangle',samples,exactTreeCount:counts.size,simultaneousHoeffdingAlpha:alpha,absoluteProbabilityBound:bound,maxTreeError,maxEdgeError,treeCounts:Object.fromEntries(counts),edgeCounts,exactEdgeProbabilities:exact.marginals});
 }
 const samples=12000,exact=enumerate(2,2,false),counts=new Map(exact.counts);for(let i=0;i<samples;i++){const a=actual(2,2,0,false,'biased-'+i,Infinity,true),key=inspect(a.par,2,2,0,false).edges.join('|');counts.set(key,counts.get(key)+1);}const wrongBiasError=Math.max(...[...counts.values()].map(n=>Math.abs(n/samples-.25)));assert(wrongBiasError>.05);return{rows,wrongBiasError,interpretation:'The simultaneous bounds assume independent sampling for their probability interpretation. Fixed seeded PRNG regression data do not prove PRNG independence or literal uniformity over all seeds.'};}
async function main(){
 const statistical=sampling(),injected=source.replace('        aspect(s)',"        auditRead(){return {W,H,rootIx,wrap,par:par&&Array.from(par),depth:depth&&Array.from(depth),path,maxDepth,building,steps:wil?.steps()};},\n        aspect(s)");assert.notEqual(source,injected);const html=fs.readFileSync(path.join(root,'dist/studio.html'),'utf8');assert(html.includes(source));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ust-review-')),file=path.join(dir,'studio.html');fs.writeFileSync(file,html.replace(source,injected).replace('generatePalette, register, boot,','generatePalette, register, auditInstances:()=>instances, boot,'));
 const browser=await chromium.launch(),cases=[];
 try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto('file://'+file+'#ust/review');await page.evaluate(()=>Studio.ready);
 const fixtures=[{grid:24,aspect:'1:1',topo:'plane',root:'corner',view:'tree'},{grid:32,aspect:'4:5',topo:'plane',root:'center',view:'branch'},{grid:40,aspect:'5:4',topo:'plane',root:'random',view:'path'},{grid:28,aspect:'1:1',topo:'plane',root:'corner',view:'maze'},{grid:48,aspect:'1:1',topo:'torus',root:'random',view:'branch'},{grid:32,aspect:'4:5',topo:'torus',root:'center',view:'maze'}];
 for(let i=0;i<fixtures.length;i++){
  const seed='ust-review-'+i,params={...fixtures[i],grain:0,mark:true,cycles:2,weight:1.1,shift:1,dim:.3,margin:.06};await page.evaluate(({seed,params})=>location.hash='ust/'+seed+'/'+btoa(JSON.stringify({...params,v:2})),{seed,params});await page.waitForFunction(seed=>Studio.getRecipe()?.seed===seed&&Studio.auditInstances().ust.inst.auditRead().par&&!Studio.auditInstances().ust.inst.auditRead().building,seed);
  const a=await page.evaluate(()=>Studio.auditInstances().ust.inst.auditRead()),s=await page.evaluate(()=>JSON.parse(JSON.stringify(Studio.auditInstances().ust.state))),ref=reference(a.W,a.H,a.rootIx,a.wrap,makeRng(seed+'/wilson')),independent=inspect(a.par,a.W,a.H,a.rootIx,a.wrap);assert.deepEqual(a.par,ref.par);assert.equal(a.steps,ref.walks);assert.deepEqual(a.depth,independent.depth);assert.equal(a.maxDepth,independent.maxDepth);
  const chunked=actual(a.W,a.H,a.rootIx,a.wrap,seed+'/wilson',0);assert.deepEqual(chunked.par,a.par);const corrupt=a.par.slice(),child=corrupt.findIndex(v=>v===a.rootIx);corrupt[a.rootIx]=child;assert.throws(()=>inspect(corrupt,a.W,a.H,a.rootIx,a.wrap));
  const w=s.aspect==='4:5'?1920:2400,h=s.aspect==='5:4'?1920:2400,expected=geometry(s,ref.par,a.W,a.H,a.rootIx,w,h);assert.deepEqual(a.path,expected.path);
  const before=await page.evaluate(()=>JSON.stringify({recipe:Studio.getRecipe(),a:Studio.auditInstances().ust.inst.auditRead()})),print=await page.evaluate(PRINT,{expected,w,h});assert.equal(before,await page.evaluate(()=>JSON.stringify({recipe:Studio.getRecipe(),a:Studio.auditInstances().ust.inst.auditRead()})));
  cases.push({seed,parameters:s,grid:[a.W,a.H],root:a.rootIx,edges:ref.par.length-1,parentSha256:sha(JSON.stringify(ref.par)),walkSteps:ref.walks,maxDepth:independent.maxDepth,pathLength:expected.path.length-1,exactReferenceMatch:true,chunkingPreserved:true,cycleControlRejected:true,print,statePreserved:true});console.log('PASS '+seed);
 }
 assert.deepEqual(errors,[]);const result={date:new Date().toISOString().slice(0,10),sourceSha256:sha(source),engineSha256:sha(engine),scope:'Finite Wilson sampler, exact small-graph enumeration and six complete rendered recipes with all edges, depths, path and print geometry checked. Uniformity theorem assumes independent ideal random draws; finite PRNG samples and SLE scaling are separate.',statistical,cases,environment:{node:process.version,chromium:browser.version(),platform:process.platform},passed:true};if(process.argv.includes('--write'))fs.writeFileSync(path.join(root,'validation/results/ust-review.json'),JSON.stringify(result,null,2)+'\n');console.log('PASS spanning-tree numerical and print review');
 }finally{await browser.close();fs.rmSync(dir,{recursive:true,force:true});}
}
const PRINT=async({expected,w,h})=>{
 const e=Studio.auditInstances().ust,s=e.state,blob=await e.inst.exportPNG(w,h),bitmap=await createImageBitmap(blob),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(bitmap,0,0);bitmap.close();const actual=ctx.getImageData(0,0,w,h).data;ctx.fillStyle=s.bg;ctx.fillRect(0,0,w,h);ctx.lineJoin='round';
 for(const g of expected.groups){ctx.strokeStyle=g.color;ctx.lineWidth=g.width;ctx.lineCap=g.cap;ctx.beginPath();for(let i=0;i<g.seg.length;i+=4){ctx.moveTo(g.seg[i],g.seg[i+1]);ctx.lineTo(g.seg[i+2],g.seg[i+3]);}ctx.stroke();}
 for(const d of expected.dots){ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,2*Math.PI);ctx.fillStyle=d.color;ctx.fill();}
 const reference=ctx.getImageData(0,0,w,h).data;let max=0,sum=0,wrong=0;for(let i=0;i<actual.length;i++){const d=Math.abs(actual[i]-reference[i]);max=Math.max(max,d);sum+=d;if(Math.abs(actual[i]-reference[(i+4)%reference.length])>2)wrong++;}if(max>1||wrong<100)throw Error(JSON.stringify({max,mean:sum/actual.length,wrong}));
 const svg=new DOMParser().parseFromString(await(await e.inst.exportSVG(w,h)).text(),'image/svg+xml'),paths=[...svg.querySelectorAll('path')],circles=[...svg.querySelectorAll('circle')];if(paths.length!==expected.groups.length||circles.length!==expected.dots.length)throw Error('Wrong vector group count');let coordinateError=0,coordinates=0;
 paths.forEach((p,i)=>{const g=expected.groups[i],values=p.getAttribute('d').match(/-?\d+(?:\.\d+)?/g).map(Number);if(values.length!==g.seg.length||p.getAttribute('stroke').toLowerCase()!==g.color.toLowerCase()||p.getAttribute('stroke-linecap')!==g.cap)throw Error('Wrong vector geometry or ink');for(let j=0;j<values.length;j++){coordinateError=Math.max(coordinateError,Math.abs(values[j]-g.seg[j]));coordinates++;}if(Math.abs(Number(p.getAttribute('stroke-width'))-g.width)>.00501)throw Error('Wrong stroke width');});
 circles.forEach((p,i)=>{const d=expected.dots[i];for(const [attr,value]of[['cx',d.x],['cy',d.y],['r',d.r]]){coordinateError=Math.max(coordinateError,Math.abs(Number(p.getAttribute(attr))-value));coordinates++;}if(p.getAttribute('fill').toLowerCase()!==d.color.toLowerCase())throw Error('Wrong root or endpoint ink');});if(coordinateError>.00501)throw Error('Vector coordinate error '+coordinateError);
 return{width:w,height:h,maxChannelError:max,meanChannelError:sum/actual.length,channelsChecked:actual.length,shiftedPrintFailureChannels:wrong,svgCoordinates:coordinates,maxSvgCoordinateError:coordinateError};
};
main().catch(e=>{console.error(e);process.exitCode=1;});
