"""Shared helpers for the proof program's Python side (untrusted: it prepares inputs and compares with floating-point
references; every rigorous statement is made by ap_proof).

Layouts: the Python model (tp06_19d, hybrid) uses physical units, state-major (state a of cell k at a*N + k);
ap_proof uses scaled variables z = x / 2^SCALE_EXP[a], cell-major (cell k at 19k + a).
"""
import json, os, subprocess, sys, time
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
AP = os.path.dirname(HERE)
sys.path.insert(0, AP)
import tp06_19d as M  # noqa: E402
from hybrid import Ring, run  # noqa: E402

SCALE_EXP = np.array([6, 0, -1, -3, 0, 0, -1, 0, 0, 0, 0, -1, -1, 0, -10, 2, 1, 4, 7])


def to_capd(x, N):
    """physical state-major (19N,) -> scaled cell-major (19N,)"""
    Y = np.asarray(x, float).reshape(19, N)
    return np.array([Y[a, k] / 2.0 ** SCALE_EXP[a] for k in range(N) for a in range(19)])


def from_capd(z, N):
    z = np.asarray(z, float)
    Y = np.empty((19, N))
    for k in range(N):
        for a in range(19):
            Y[a, k] = z[19 * k + a] * 2.0 ** SCALE_EXP[a]
    return Y.ravel()


def write_box(path, z, rel=1e-10, absmin=0.0, point_rows=()):
    """box z_i +- max(rel |z_i|, absmin) (exact: the radius is a double); rows in point_rows are points"""
    with open(path, "w") as f:
        f.write("# box (scaled, cell-major), radius %g relative\n" % rel)
        f.write("%d\n" % len(z))
        for i, v in enumerate(z):
            r = 0.0 if i in point_rows else max(rel * abs(v), absmin)
            f.write("%s %s\n" % (float(v - r).hex(), float(v + r).hex()))


def read_out(path):
    """segment/chain output: (kind, ok, T(lo,hi), X lo/hi arrays, D lo/hi or None, diff lo/hi or None)"""
    L = open(path).read().split("\n")
    kind, ok = L[0].split()
    T = tuple(_num(t) for t in L[1].split())
    n = int(L[2])
    X = np.array([[_num(t) for t in L[3 + i].split()] for i in range(n)])
    p = 3 + n
    D = diff = None
    if p < len(L) and L[p].strip() and L[p].strip() != "diff":
        r, c = map(int, L[p].split())
        D = np.array([[_num(t) for t in L[p + 1 + i].split()] for i in range(r * c)]).reshape(r, c, 2)
        p += 1 + r * c
    if p < len(L) and L[p].strip() == "diff":
        m = int(L[p + 1])
        diff = np.array([[_num(t) for t in L[p + 2 + i].split()] for i in range(m)])
    return dict(kind=kind, ok=ok == "1", T=T, X=X, D=D, diff=diff)


def _num(t):
    if "#" in t:  # MPFR base-16 string m@e#prec -> nearest double (for comparisons only)
        m, rest = t.split("@")
        e = int(rest.split("#")[0])
        neg = m.startswith("-")
        m = m.lstrip("-")
        v = 0.0
        import mpmath as mp
        mp.mp.prec = 300
        val = mp.mpf(int(m, 16)) * mp.mpf(16) ** (e - len(m))
        return float(-val if neg else val)
    return float.fromhex(t)


def write_plan(path, N, coupling, segments, **kw):
    lines = ["# ap_proof plan (generated by %s)" % os.path.basename(sys.argv[0]), "N %d" % N, "coupling %s" % coupling]
    for k, v in kw.items():
        lines.append("%s %s" % (k, v))
    lines += segments
    open(path, "w").write("\n".join(lines) + "\n")


def run_ap(binary, args, log, timeout):
    t = time.time()
    r = subprocess.run([binary] + args, capture_output=True, text=True, timeout=timeout)
    with open(log, "a") as f:
        f.write("$ %s %s\n%s%s(rc %s, %.1f s)\n" % (os.path.basename(binary), " ".join(args), r.stdout, r.stderr, r.returncode, time.time() - t))
    return r.returncode, r.stdout + r.stderr, time.time() - t


def inside(ref, X, slack_rel=0.0):
    lo, hi = X[:, 0], X[:, 1]
    s = slack_rel * np.abs(ref)
    ok = (ref >= lo - s) & (ref <= hi + s)
    mid = 0.5 * (lo + hi)
    rad = 0.5 * (hi - lo)
    dist_out = np.maximum(0, np.maximum(lo - ref, ref - hi))
    return bool(ok.all()), dict(max_out_over_radius=float(np.max(dist_out / np.maximum(rad, 1e-300))),
                                max_rel_dist_to_mid=float(np.max(np.abs(mid - ref) / np.maximum(np.abs(ref), 1e-300))),
                                max_rel_width=float(np.max((hi - lo) / np.maximum(np.abs(mid), 1e-300))))


def run_ap_rss(binary, args, log, timeout, as_cap_gb=None):
    """Like run_ap, and also returns the child's peak resident set (GiB, from wait4). Output goes to the log file.
    With as_cap_gb the child runs under an address-space cap (RLIMIT_AS). On timeout the child is killed."""
    import resource, signal
    t = time.time()
    with open(log, "a") as lf:
        lf.write("$ %s %s\n" % (os.path.basename(binary), " ".join(args)))
        lf.flush()

        def pre():
            if as_cap_gb:
                cap = int(as_cap_gb * 2 ** 30)
                resource.setrlimit(resource.RLIMIT_AS, (cap, cap))
        pr = subprocess.Popen([binary] + args, stdout=lf, stderr=subprocess.STDOUT, preexec_fn=pre)
        rc, ru = None, None
        while True:
            pid, status, ru = os.wait4(pr.pid, os.WNOHANG)
            if pid != 0:
                rc = os.waitstatus_to_exitcode(status)
                break
            if time.time() - t > timeout:
                pr.send_signal(signal.SIGKILL)
                pid, status, ru = os.wait4(pr.pid, 0)
                rc = "timeout"
                break
            time.sleep(0.5)
        pr.returncode = rc if isinstance(rc, int) else -9
        wall = time.time() - t
        lf.write("(rc %s, %.1f s, peak RSS %.3f GiB)\n" % (rc, wall, ru.ru_maxrss / 2 ** 20))
    tail = open(log).read()[-2000:]
    return rc, tail, wall, ru.ru_maxrss / 2 ** 20
